"use client";

import { AppShell } from "@/components/AppShell"; import { EmptyState } from "@/components/EmptyState"; import { Modal } from "@/components/Modal"; import { PageHeader } from "@/components/PageHeader"; import { StatusPill } from "@/components/StatusPill"; import { apiFetch, ApiError } from "@/lib/api"; import type { Client, ClientReport, Paginated } from "@/lib/types"; import { FormEvent, useCallback, useEffect, useMemo, useState } from "react";
export default function ReportsPage() {
  const [reports, setReports] = useState<ClientReport[]>([]); const [clients, setClients] = useState<Client[]>([]); const [clientId, setClientId] = useState(""); const [open, setOpen] = useState(false); const [loading, setLoading] = useState(true); const [submitting, setSubmitting] = useState(false); const [error, setError] = useState(""); const [success, setSuccess] = useState("");
  const load = useCallback(async () => { setLoading(true); try { const [reportResponse, clientResponse] = await Promise.all([apiFetch<Paginated<ClientReport>>("/reports?per_page=100"), apiFetch<Paginated<Client>>("/clients?per_page=100")]); setReports(reportResponse.data); setClients(clientResponse.data); setError(""); } catch (exception) { setError(exception instanceof ApiError ? exception.message : "Unable to load reports."); } finally { setLoading(false); } }, []); useEffect(() => { void load(); }, [load]);
  async function submit(event: FormEvent) { event.preventDefault(); setSubmitting(true); setError(""); try { await apiFetch("/reports", { method: "POST", body: JSON.stringify({ client_id: Number(clientId) }) }); setOpen(false); setSuccess("Report generation was queued. A running queue worker is required."); setClientId(""); } catch (exception) { setError(exception instanceof ApiError ? exception.message : "Unable to queue report."); } finally { setSubmitting(false); } }
  const clientById = useMemo(() => new Map(clients.map((client) => [client.id, client])), [clients]);
  return <AppShell><main className="main"><PageHeader eyebrow="Client communication" title="Reports" description="Generate stored monthly reports from data already collected for each client." actions={<button className="primary" onClick={() => setOpen(true)} disabled={clients.length === 0}>Generate report</button>} />{error && <div className="errorBox">{error}</div>}{success && <div className="successBox">{success}</div>}<section className="panel"><div className="panelHeader"><div><h2>Generated reports</h2><p>PDF rendering is not claimed until a file path is produced by a configured renderer.</p></div></div>{loading ? <div className="loadingPanel">Loading reports…</div> : reports.length === 0 ? <EmptyState title="No reports generated" description={clients.length === 0 ? "Add a client first." : "Generate a monthly report after collecting client performance data."} /> : <div className="tableWrap"><table><thead><tr><th>Client</th><th>Type</th><th>Period</th><th>Status</th><th>Generated</th><th>File</th></tr></thead><tbody>{reports.map((report) => <tr key={report.id}><td>{clientById.get(report.client_id)?.name ?? `Client #${report.client_id}`}</td><td>{report.type.replaceAll("_", " ")}</td><td>{report.period_start} → {report.period_end}</td><td><StatusPill value={report.status} /></td><td>{report.generated_at ? new Date(report.generated_at).toLocaleString() : "—"}</td><td>{report.file_path ? "Available" : "Data report only"}</td></tr>)}</tbody></table></div>}</section><Modal title="Generate monthly report" open={open} onClose={() => setOpen(false)}><form className="formStack" onSubmit={submit}><label>Active client<select value={clientId} onChange={(event) => setClientId(event.target.value)} required><option value="">Select client</option>{clients.map((client) => <option key={client.id} value={client.id}>{client.name} ({client.status})</option>)}</select><small>The current generator creates the previous calendar month and processes active clients.</small></label><div className="modalActions"><button type="button" className="secondary" onClick={() => setOpen(false)}>Cancel</button><button className="primary" disabled={submitting}>{submitting ? "Queuing…" : "Queue report"}</button></div></form></Modal></main></AppShell>;
}
